### PR TITLE
Bump runtime to 21.08 and update Nuspell to 5.1.0

### PR DESCRIPTION
**Pull request by bbhtt**
20.08 will be EOL this August.

### CODE REVIEW

**Comment by dimztimz** [comment]
You may as well add code that enables the permission to read the home directory.

**Comment by bbhtt** [comment]
> You may as well add code that enables the permission to read the home directory.

Sure, this needs only read-only access, right?

**Comment by dimztimz** [comment]
> > You may as well add code that enables the permission to read the home directory.
> 
> Sure, this needs only read-only access, right?

Yes, only read access.

**Comment by dimztimz** [comment]
I merged this but the building bot seems unresponsive. It only works in the PR but not in the main repo, it is silent. See the commit history, there are no green checkmarks.

**Comment by dimztimz** [comment]
Ok, seems like it's fixed.

**Pull request merged**
